owner: SpreadSheets600
repo: Uptime-Monitor

sites:
  - name: Cooked Roasted Life Backend
    url: https://cooked-roasted-life.onrender.com
  - name: Portfolio ( Personal Website )
    url: https://spreadsheet600.github.io
  - name: PoraHobe website
    url: https://dono-03.danbot.host:2521

status-website:
  baseUrl: /upptime-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime Monitor
  introTitle: My Website And Backends Upptime Status Page
  introMessage: Powered by [Upptime](https://upptime.js.org)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
