owner: SpreadSheets600
repo: Uptime-Monitor

sites:
  - name: Portfolio ( Personal Website )
    url: https://spreadsheets600.buzz/
  - name: Portfolio Blogs ( Blogs Website )
    url: https://blogs.spreadsheets600.buzz/
  - name: Pora Hobe
    url: https://porahobe.spreadsheets600.buzz/
  - name: Frontpage Generator
    url: https://frontpage-generator.pages.dev/
  - name: Frontpage Generator API
    url: https://frontpage-api.spreadsheets600.workers.dev/
status-website:
  theme: light
  baseUrl: /Uptime-Monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  themeUrl: https://spreadsheets600.is-a.dev/Uptime-Monitor/assets/theme.css
  name: Upptime Monitor
  introTitle: My Services And Website Uptime Monitor
  introMessage: Powered By [Upptime](https://upptime.js.org)
  navbar:
    - title: GitHub
      href: https://github.com/spreadsheets600
  i18n:
    footer: SpreadSheets600 // Powered By [Upptime](https://upptime.js.org)
